#!/bin/sh
# PVE LXC sidecar router (旁路由), single NIC on eth0.

LAN_IP="192.168.7.3"
LAN_NETMASK="255.255.255.0"
LAN_GATEWAY="192.168.7.1"
LAN_DNS="192.168.7.1"

uci -q delete network.wan
uci -q delete network.wan6

uci set network.lan.proto='static'
uci set network.lan.ipaddr="$LAN_IP"
uci set network.lan.netmask="$LAN_NETMASK"
uci set network.lan.gateway="$LAN_GATEWAY"
uci set network.lan.dns="$LAN_DNS"
uci -q delete network.lan.ip6assign
uci set network.lan.force_link='1'
uci set network.lan.ipv6='0'
uci -q delete network.globals.ula_prefix

uci set dhcp.lan.ignore='1'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ndp='disabled'
uci -q delete dhcp.wan

uci set firewall.@defaults[0].input='ACCEPT'
uci set firewall.@defaults[0].output='ACCEPT'
uci set firewall.@defaults[0].forward='ACCEPT'
uci set firewall.@defaults[0].flow_offloading='0'

while uci -q delete firewall.@forwarding[0]; do :; done

i=0
while [ "$i" -lt 16 ]; do
	name="$(uci -q get firewall.@zone[$i].name || true)"
	if [ "$name" = "wan" ]; then
		uci -q delete firewall.@zone[$i]
		continue
	fi
	if [ "$name" = "lan" ]; then
		uci set firewall.@zone[$i].input='ACCEPT'
		uci set firewall.@zone[$i].output='ACCEPT'
		uci set firewall.@zone[$i].forward='ACCEPT'
		uci -q delete firewall.@zone[$i].masq
		uci -q delete firewall.@zone[$i].mtu_fix
	fi
	i=$((i + 1))
done

uci set system.@system[0].hostname='openwrt'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'

uci set luci.main.lang='zh_cn'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci -q set istorex.@istorex[0].model='router'
uci -q set istorex.@istorex[0].enabled='1'

uci -q set upnpd.config.enabled='1'
uci -q set upnpd.config.enable_upnp='1'
uci -q set upnpd.config.enable_natpmp='1'
uci -q set upnpd.config.internal_iface='lan'
uci -q set upnpd.config.external_iface='lan'
uci -q set upnpd.config.ext_allow_private_ipv4='1'
uci -q set upnpd.config.igdv1='1'

[ -x /etc/init.d/tasks ] && /etc/init.d/tasks enable
[ -x /etc/init.d/tasks ] && /etc/init.d/tasks start
[ -x /etc/init.d/quickstart ] && /etc/init.d/quickstart enable
[ -x /etc/init.d/quickstart ] && /etc/init.d/quickstart start

uci -q set argon.@global[0].online_wallpaper='none'
if [ -f /usr/share/argon-bg.jpg ]; then
	mkdir -p /www/luci-static/argon/background
	rm -f /www/luci-static/argon/background/*.jpg \
		/www/luci-static/argon/background/*.png \
		/www/luci-static/argon/background/*.gif \
		/www/luci-static/argon/background/*.webp \
		/www/luci-static/argon/background/*.mp4
	cp -f /usr/share/argon-bg.jpg /www/luci-static/argon/background/bg.jpg
fi

uci commit network
uci commit dhcp
uci commit firewall
uci commit system
uci commit luci
uci commit istorex
uci commit upnpd
uci -q commit argon

exit 0
